//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClinic.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int Id { get; set; }
        public Nullable<int> Id_Animal { get; set; }
        public Nullable<int> Id_Doctor { get; set; }
        public Nullable<System.DateTime> Date_admission { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
